### PR TITLE
feat: Update Clevertap SDK to Version 5.x

### PR DESCRIPTION
**Pull request by BrandonStalnaker**
## Summary
 - Update to use Clevertap 5.x

 ## Testing Plan
 - Confirmed locally and tested end to end for a day (didn't see any problems) until I seemed to get locked out of our clevertap account.

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-5877

### CODE REVIEW

**Comment by akashvercetti** [comment]
@BrandonStalnaker I think the `Cartfile` needs to be updated from `~> 4.2` to `~> 5.2`

**Review by einsteinx2 — APPROVED** [review]
LGTM

**Review by samdozor — APPROVED** [review]
just confirming - did you check that we aren't using any of the newly deprecated APIs in 5.x? if so, lgtm

**Comment by BrandonStalnaker** [comment]
@samdozor I confirmed we weren't using any of these https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md#deprecated and didn't notice any new warnings.

**Pull request merged**
