### PR TITLE
chore: bump clevertap-ios-sdk from 3.9 to 4.2.0

### PR DESCRIPTION
**Pull request by Sonal-Kachare**
Bumps [clevertap-ios-sdk](https://github.com/CleverTap/clevertap-ios-sdk) from 3.9 to 4.2.0.

- [Release notes](https://github.com/CleverTap/clevertap-ios-sdk/releases)
- [Changelog](https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md#version-420-december-13-2022)

### CODE REVIEW

**Comment by Sonal-Kachare** [comment]
Hi @peterjenkins

Could you please review the PR?
Hoping to get it merged, Thank you!

**Comment by Sonal-Kachare** [comment]
Hi @peterjenkins 

Any update here?
Also if you are busy, could you suggest me point of contact?

**Comment by shwangMP** [comment]
Hey @Sonal-Kachare - Thanks for raising! I've passed this on to our team to get a review. Please tag me with any questions

**Comment by einsteinx2** [comment]
Thank you for the PR!

**Pull request merged**
