### PR TITLE
chore: Update clevertap ios sdk to v5.x

### PR DESCRIPTION
**Pull request by AishwaryaNanna**
## Summary
 - Update clevertap-ios-sdk to v5.2.2 
-  Update clevertap kit to track library name and version

 ## Testing Plan
 - This was tested locally and working fine.

### CODE REVIEW

**Comment by AishwaryaNanna** [comment]
Hi @BrandonStalnaker ,
Can you please review this PR?
Hoping to get it merged.

Thanks!

**Comment by einsteinx2** [comment]
Brandon released an update yesterday bumping the SDK version to 5.2 in this PR: https://github.com/mparticle-integrations/mparticle-apple-integration-clevertap/pull/11

I see that your PR also adds support for setting the custom library/version on Clevertap SDK based on the MP Kit's version. In order to use this we would need to update our release CI action to handle this automatically so unfortunately we can't accept this implementation.

What's the use case for setting those values? I can get a ticket opened internally to get this into our work queue, but I need some details around the necessity here so I can get it prioritized. Thanks.

**Comment by akashvercetti** [comment]
@einsteinx2 @BrandonStalnaker, The `setLibrary` method is used to track internally at CleverTap, the version of the Mparticle (or any auxillary SDK) that the customer is using, so that we can plan future updates based on this data.

Also, the PR #11 does not contain updates to the Cartfile. It still points to 4.x. We have made the Cartfile changes in this PR.

**Comment by akashvercetti** [comment]
@einsteinx2 Did you get a chance to review this?

**Comment by akashvercetti** [comment]
@einsteinx2 @BrandonStalnaker Could you please take a look at this PR? We need to get this expedited for our clients.
I have provided the explanation/differences in an earlier comment.

**Comment by einsteinx2** [comment]
@akashvercetti apologies for the delay due to the holidays. I just put up another PR here which implements this in a way we can use it (the CI action will update the version number automatically): https://github.com/mparticle-integrations/mparticle-apple-integration-clevertap/pull/13

@BrandonStalnaker is out today, but he'll be able to review it on Monday and we should be able to release that same day.

Closing this in favor of the other PR.

**Pull request closed without merging**
